title: Installs
modelClass: Android\Installs\Models\Install
list: $/android/installs/models/install/columns.yaml
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
