plugin:
    name: 'android.installs::lang.plugin.name'
    description: 'android.installs::lang.plugin.description'
    author: Android
    icon: oc-icon-android
    homepage: 'tempestronics.com'
permissions:
    android.installs.view_installs:
        tab: 'android.installs::lang.plugin.full_name'
        label: 'android.installs::lang.install.view_installs'
navigation:
    android:
        label: 'android.installs::lang.plugin.android'
        url: android/installs/installs
        icon: icon-android
        permissions: {  }
        sideMenu:
            installs:
                label: 'android.installs::lang.plugin.name'
                url: android/installs/installs
                icon: icon-user-plus
                permissions:
                    - android.installs.view_installs
